import type { Atom } from './types';

export const ATOMS: Omit<Atom, 'instanceId' | 'x' | 'y'>[] = [
  // Group 1: Alkali Metals (except Hydrogen) - bg-red-500
  { id: 'H', name: 'هيدروجين', symbol: 'H', color: 'bg-slate-300', textColor: 'text-slate-800', radius: 20, valency: '+1, -1', oxidationStates: [+1, -1] },
  { id: 'Li', name: 'ليثيوم', symbol: 'Li', color: 'bg-red-500', textColor: 'text-white', radius: 23, valency: '+1', oxidationStates: [+1] },
  { id: 'Na', name: 'صوديوم', symbol: 'Na', color: 'bg-red-500', textColor: 'text-white', radius: 25, valency: '+1', oxidationStates: [+1] },
  { id: 'K', name: 'بوتاسيوم', symbol: 'K', color: 'bg-red-500', textColor: 'text-white', radius: 32, valency: '+1', oxidationStates: [+1] },
  { id: 'Rb', name: 'روبيديوم', symbol: 'Rb', color: 'bg-red-500', textColor: 'text-white', radius: 38, valency: '+1', oxidationStates: [+1] },
  { id: 'Cs', name: 'سيزيوم', symbol: 'Cs', color: 'bg-red-500', textColor: 'text-white', radius: 42, valency: '+1', oxidationStates: [+1] },
  { id: 'Fr', name: 'فرانسيوم', symbol: 'Fr', color: 'bg-red-500', textColor: 'text-white', radius: 43, valency: '+1', oxidationStates: [+1] },

  // Group 2: Alkaline Earth Metals - bg-orange-500
  { id: 'Be', name: 'بيريليوم', symbol: 'Be', color: 'bg-orange-500', textColor: 'text-white', radius: 26, valency: '+2', oxidationStates: [+2] },
  { id: 'Mg', name: 'مغنيسيوم', symbol: 'Mg', color: 'bg-orange-500', textColor: 'text-white', radius: 30, valency: '+2', oxidationStates: [+2] },
  { id: 'Ca', name: 'كالسيوم', symbol: 'Ca', color: 'bg-orange-500', textColor: 'text-white', radius: 38, valency: '+2', oxidationStates: [+2] },
  { id: 'Sr', name: 'سترونشيوم', symbol: 'Sr', color: 'bg-orange-500', textColor: 'text-white', radius: 40, valency: '+2', oxidationStates: [+2] },
  { id: 'Ba', name: 'باريوم', symbol: 'Ba', color: 'bg-orange-500', textColor: 'text-white', radius: 43, valency: '+2', oxidationStates: [+2] },
  { id: 'Ra', name: 'راديوم', symbol: 'Ra', color: 'bg-orange-500', textColor: 'text-white', radius: 44, valency: '+2', oxidationStates: [+2] },

  // Group 3-12: Transition Metals - bg-yellow-500
  { id: 'Sc', name: 'سكانديوم', symbol: 'Sc', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 32, valency: '+3', oxidationStates: [+3] },
  { id: 'Ti', name: 'تيتانيوم', symbol: 'Ti', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 31, valency: '+4, +3', oxidationStates: [+4, +3] },
  { id: 'V', name: 'فاناديوم', symbol: 'V', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 30, valency: '+5, +4', oxidationStates: [+5, +4, +3, +2] },
  { id: 'Cr', name: 'كروم', symbol: 'Cr', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 29, valency: '+3, +6, +2', oxidationStates: [+2, +3, +6] },
  { id: 'Mn', name: 'منغنيز', symbol: 'Mn', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 28, valency: '+2, +4, +7', oxidationStates: [+2, +3, +4, +6, +7] },
  { id: 'Fe', name: 'حديد', symbol: 'Fe', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+3, +2', oxidationStates: [+2, +3] },
  { id: 'Co', name: 'كوبالت', symbol: 'Co', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 27, valency: '+2, +3', oxidationStates: [+2, +3] },
  { id: 'Ni', name: 'نيكل', symbol: 'Ni', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 26, valency: '+2', oxidationStates: [+2] },
  { id: 'Cu', name: 'نحاس', symbol: 'Cu', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 26, valency: '+2, +1', oxidationStates: [+1, +2] },
  { id: 'Zn', name: 'زنك', symbol: 'Zn', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 27, valency: '+2', oxidationStates: [+2] },
  { id: 'Y', name: 'إيتريوم', symbol: 'Y', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+3', oxidationStates: [+3] },
  { id: 'Zr', name: 'زركونيوم', symbol: 'Zr', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+4', oxidationStates: [+4] },
  { id: 'Nb', name: 'نيوبيوم', symbol: 'Nb', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+5', oxidationStates: [+5, +3] },
  { id: 'Mo', name: 'موليبدنوم', symbol: 'Mo', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+6', oxidationStates: [+2, +3, +4, +5, +6] },
  { id: 'Tc', name: 'تكنيشيوم', symbol: 'Tc', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 32, valency: '+7, +4', oxidationStates: [+4, +7] },
  { id: 'Ru', name: 'روثينيوم', symbol: 'Ru', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 31, valency: '+3, +4', oxidationStates: [+2, +3, +4, +6, +8] },
  { id: 'Rh', name: 'روديوم', symbol: 'Rh', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 30, valency: '+3', oxidationStates: [+2, +3, +4] },
  { id: 'Pd', name: 'بلاديوم', symbol: 'Pd', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 29, valency: '+2, +4', oxidationStates: [+2, +4] },
  { id: 'Ag', name: 'فضة', symbol: 'Ag', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+1', oxidationStates: [+1] },
  { id: 'Cd', name: 'كادميوم', symbol: 'Cd', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+2', oxidationStates: [+2] },
  { id: 'Hf', name: 'هافنيوم', symbol: 'Hf', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+4', oxidationStates: [+4] },
  { id: 'Ta', name: 'تانتالوم', symbol: 'Ta', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+5', oxidationStates: [+5] },
  { id: 'W', name: 'تنغستن', symbol: 'W', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+6', oxidationStates: [+2, +3, +4, +5, +6] },
  { id: 'Re', name: 'رينيوم', symbol: 'Re', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 32, valency: '+7, +4', oxidationStates: [-1, +1, +2, +3, +4, +5, +6, +7] },
  { id: 'Os', name: 'أوزميوم', symbol: 'Os', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 31, valency: '+4, +8', oxidationStates: [+2, +3, +4, +6, +8] },
  { id: 'Ir', name: 'إريديوم', symbol: 'Ir', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 30, valency: '+4, +3', oxidationStates: [+2, +3, +4, +6] },
  { id: 'Pt', name: 'بلاتين', symbol: 'Pt', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 29, valency: '+4, +2', oxidationStates: [+2, +4] },
  { id: 'Au', name: 'ذهب', symbol: 'Au', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+3, +1', oxidationStates: [+1, +3] },
  { id: 'Hg', name: 'زئبق', symbol: 'Hg', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 37, valency: '+2, +1', oxidationStates: [+1, +2] },
  { id: 'Rf', name: 'رذرفورديوم', symbol: 'Rf', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+4', oxidationStates: [+4] },
  { id: 'Db', name: 'دوبنيوم', symbol: 'Db', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+5', oxidationStates: [+5] },
  { id: 'Sg', name: 'سيبورجيوم', symbol: 'Sg', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+6', oxidationStates: [+6] },
  { id: 'Bh', name: 'بوريوم', symbol: 'Bh', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+7', oxidationStates: [+7] },
  { id: 'Hs', name: 'هاسيوم', symbol: 'Hs', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 32, valency: '+8', oxidationStates: [+8] },
  { id: 'Mt', name: 'مايتنريوم', symbol: 'Mt', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 31, valency: 'unknown', oxidationStates: [] },
  { id: 'Ds', name: 'دارمشتادتيوم', symbol: 'Ds', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 30, valency: 'unknown', oxidationStates: [] },
  { id: 'Rg', name: 'رونتجينيوم', symbol: 'Rg', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 29, valency: 'unknown', oxidationStates: [] },
  { id: 'Cn', name: 'كوبرنيسيوم', symbol: 'Cn', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 28, valency: '+2', oxidationStates: [+2] },

  // Group 13: Boron Group - bg-green-300
  { id: 'B', name: 'بورون', symbol: 'B', color: 'bg-green-300', textColor: 'text-slate-800', radius: 24, valency: '+3', oxidationStates: [+3] },
  { id: 'Al', name: 'ألومنيوم', symbol: 'Al', color: 'bg-green-300', textColor: 'text-slate-800', radius: 33, valency: '+3', oxidationStates: [+3] },
  { id: 'Ga', name: 'غاليوم', symbol: 'Ga', color: 'bg-green-300', textColor: 'text-slate-800', radius: 32, valency: '+3', oxidationStates: [+3] },
  { id: 'In', name: 'إنديوم', symbol: 'In', color: 'bg-green-300', textColor: 'text-slate-800', radius: 36, valency: '+3', oxidationStates: [+1, +3] },
  { id: 'Tl', name: 'ثاليوم', symbol: 'Tl', color: 'bg-green-300', textColor: 'text-slate-800', radius: 37, valency: '+1, +3', oxidationStates: [+1, +3] },
  { id: 'Nh', name: 'نيهونيوم', symbol: 'Nh', color: 'bg-green-300', textColor: 'text-slate-800', radius: 38, valency: 'unknown', oxidationStates: [] },

  // Group 14: Carbon Group - bg-slate-500
  { id: 'C', name: 'كربون', symbol: 'C', color: 'bg-slate-500', textColor: 'text-white', radius: 35, valency: '+4, -4', oxidationStates: [-4, -2, 0, +2, +4] },
  { id: 'Si', name: 'سيليكون', symbol: 'Si', color: 'bg-slate-500', textColor: 'text-white', radius: 36, valency: '+4, -4', oxidationStates: [-4, +2, +4] },
  { id: 'Ge', name: 'جرمانيوم', symbol: 'Ge', color: 'bg-slate-500', textColor: 'text-white', radius: 34, valency: '+4', oxidationStates: [+2, +4] },
  { id: 'Sn', name: 'قصدير', symbol: 'Sn', color: 'bg-slate-500', textColor: 'text-white', radius: 37, valency: '+4, +2', oxidationStates: [+2, +4] },
  { id: 'Pb', name: 'رصاص', symbol: 'Pb', color: 'bg-slate-500', textColor: 'text-white', radius: 39, valency: '+4, +2', oxidationStates: [+2, +4] },
  { id: 'Fl', name: 'فليروفيوم', symbol: 'Fl', color: 'bg-slate-500', textColor: 'text-white', radius: 39, valency: 'unknown', oxidationStates: [] },

  // Group 15: Pnictogens - bg-blue-500
  { id: 'N', name: 'نيتروجين', symbol: 'N', color: 'bg-blue-500', textColor: 'text-white', radius: 28, valency: '-3', oxidationStates: [-3, -2, -1, +1, +2, +3, +4, +5] },
  { id: 'P', name: 'فوسفور', symbol: 'P', color: 'bg-blue-500', textColor: 'text-white', radius: 29, valency: '-3, +5, +3', oxidationStates: [-3, +1, +3, +5] },
  { id: 'As', name: 'زرنيخ', symbol: 'As', color: 'bg-blue-500', textColor: 'text-white', radius: 31, valency: '-3, +5, +3', oxidationStates: [-3, +3, +5] },
  { id: 'Sb', name: 'إثمد', symbol: 'Sb', color: 'bg-blue-500', textColor: 'text-white', radius: 35, valency: '+3, +5', oxidationStates: [-3, +3, +5] },
  { id: 'Bi', name: 'بزموث', symbol: 'Bi', color: 'bg-blue-500', textColor: 'text-white', radius: 37, valency: '+3, +5', oxidationStates: [+3, +5] },
  { id: 'Mc', name: 'موسكوفيوم', symbol: 'Mc', color: 'bg-blue-500', textColor: 'text-white', radius: 38, valency: 'unknown', oxidationStates: [] },

  // Group 16: Chalcogens - bg-teal-400
  { id: 'O', name: 'أكسجين', symbol: 'O', color: 'bg-teal-400', textColor: 'text-slate-800', radius: 30, valency: '-2', oxidationStates: [-2, -1] },
  { id: 'S', name: 'كبريت', symbol: 'S', color: 'bg-teal-400', textColor: 'text-slate-800', radius: 31, valency: '-2, +6, +4', oxidationStates: [-2, 0, +2, +4, +6] },
  { id: 'Se', name: 'سيلينيوم', symbol: 'Se', color: 'bg-teal-400', textColor: 'text-slate-800', radius: 32, valency: '-2, +6, +4', oxidationStates: [-2, +2, +4, +6] },
  { id: 'Te', name: 'تيلوريوم', symbol: 'Te', color: 'bg-teal-400', textColor: 'text-slate-800', radius: 36, valency: '-2, +6, +4', oxidationStates: [-2, +2, +4, +6] },
  { id: 'Po', name: 'بولونيوم', symbol: 'Po', color: 'bg-teal-400', textColor: 'text-slate-800', radius: 37, valency: '+2, +4', oxidationStates: [+2, +4] },
  { id: 'Lv', name: 'ليفرموريوم', symbol: 'Lv', color: 'bg-teal-400', textColor: 'text-slate-800', radius: 38, valency: 'unknown', oxidationStates: [] },

  // Group 17: Halogens - bg-purple-400
  { id: 'F', name: 'فلور', symbol: 'F', color: 'bg-purple-400', textColor: 'text-slate-800', radius: 22, valency: '-1', oxidationStates: [-1] },
  { id: 'Cl', name: 'كلور', symbol: 'Cl', color: 'bg-purple-400', textColor: 'text-slate-800', radius: 27, valency: '-1', oxidationStates: [-1, +1, +3, +5, +7] },
  { id: 'Br', name: 'بروم', symbol: 'Br', color: 'bg-purple-400', textColor: 'text-slate-800', radius: 29, valency: '-1', oxidationStates: [-1, +1, +3, +5, +7] },
  { id: 'I', name: 'يود', symbol: 'I', color: 'bg-purple-400', textColor: 'text-slate-800', radius: 33, valency: '-1', oxidationStates: [-1, +1, +3, +5, +7] },
  { id: 'At', name: 'أستاتين', symbol: 'At', color: 'bg-purple-400', textColor: 'text-slate-800', radius: 35, valency: '-1', oxidationStates: [-1, +1] },
  { id: 'Ts', name: 'تينيسين', symbol: 'Ts', color: 'bg-purple-400', textColor: 'text-slate-800', radius: 36, valency: 'unknown', oxidationStates: [] },
  
  // Group 18: Noble Gases - bg-indigo-500
  { id: 'He', name: 'هيليوم', symbol: 'He', color: 'bg-indigo-500', textColor: 'text-white', radius: 21, valency: '0', oxidationStates: [0] },
  { id: 'Ne', name: 'نيون', symbol: 'Ne', color: 'bg-indigo-500', textColor: 'text-white', radius: 23, valency: '0', oxidationStates: [0] },
  { id: 'Ar', name: 'آرغون', symbol: 'Ar', color: 'bg-indigo-500', textColor: 'text-white', radius: 28, valency: '0', oxidationStates: [0] },
  { id: 'Kr', name: 'كريبتون', symbol: 'Kr', color: 'bg-indigo-500', textColor: 'text-white', radius: 30, valency: '0', oxidationStates: [0, +2] },
  { id: 'Xe', name: 'زينون', symbol: 'Xe', color: 'bg-indigo-500', textColor: 'text-white', radius: 34, valency: '0', oxidationStates: [0, +2, +4, +6, +8] },
  { id: 'Rn', name: 'رادون', symbol: 'Rn', color: 'bg-indigo-500', textColor: 'text-white', radius: 36, valency: '0', oxidationStates: [0, +2] },
  { id: 'Og', name: 'أوغانيسون', symbol: 'Og', color: 'bg-indigo-500', textColor: 'text-white', radius: 37, valency: '0', oxidationStates: [0] },

  // Lanthanides - bg-pink-400
  { id: 'La', name: 'لانثانوم', symbol: 'La', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 37, valency: '+3', oxidationStates: [+3] },
  { id: 'Ce', name: 'سيريوم', symbol: 'Ce', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 36, valency: '+3, +4', oxidationStates: [+3, +4] },
  { id: 'Pr', name: 'براسيوديميوم', symbol: 'Pr', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 36, valency: '+3', oxidationStates: [+3, +4] },
  { id: 'Nd', name: 'نيوديميوم', symbol: 'Nd', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 35, valency: '+3', oxidationStates: [+3] },
  { id: 'Pm', name: 'بروميثيوم', symbol: 'Pm', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 35, valency: '+3', oxidationStates: [+3] },
  { id: 'Sm', name: 'ساماريوم', symbol: 'Sm', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 34, valency: '+3, +2', oxidationStates: [+2, +3] },
  { id: 'Eu', name: 'يوروبيوم', symbol: 'Eu', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 34, valency: '+3, +2', oxidationStates: [+2, +3] },
  { id: 'Gd', name: 'غادولينيوم', symbol: 'Gd', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 33, valency: '+3', oxidationStates: [+3] },
  { id: 'Tb', name: 'تربيوم', symbol: 'Tb', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 33, valency: '+3', oxidationStates: [+3, +4] },
  { id: 'Dy', name: 'ديسبروسيوم', symbol: 'Dy', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 32, valency: '+3', oxidationStates: [+3] },
  { id: 'Ho', name: 'هولميوم', symbol: 'Ho', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 32, valency: '+3', oxidationStates: [+3] },
  { id: 'Er', name: 'إربيوم', symbol: 'Er', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 31, valency: '+3', oxidationStates: [+3] },
  { id: 'Tm', name: 'ثوليوم', symbol: 'Tm', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 31, valency: '+3', oxidationStates: [+3] },
  { id: 'Yb', name: 'إيتربيوم', symbol: 'Yb', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 30, valency: '+3, +2', oxidationStates: [+2, +3] },
  { id: 'Lu', name: 'لوتيتيوم', symbol: 'Lu', color: 'bg-pink-400', textColor: 'text-slate-800', radius: 30, valency: '+3', oxidationStates: [+3] },
  
  // Actinides - bg-rose-400
  { id: 'Ac', name: 'أكتينيوم', symbol: 'Ac', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 38, valency: '+3', oxidationStates: [+3] },
  { id: 'Th', name: 'ثوريوم', symbol: 'Th', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 37, valency: '+4', oxidationStates: [+4] },
  { id: 'Pa', name: 'بروتكتينيوم', symbol: 'Pa', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 36, valency: '+5, +4', oxidationStates: [+4, +5] },
  { id: 'U', name: 'يورانيوم', symbol: 'U', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 35, valency: '+6, +4', oxidationStates: [+3, +4, +5, +6] },
  { id: 'Np', name: 'نبتونيوم', symbol: 'Np', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 34, valency: '+5, +4', oxidationStates: [+3, +4, +5, +6] },
  { id: 'Pu', name: 'بلوتونيوم', symbol: 'Pu', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 33, valency: '+4', oxidationStates: [+3, +4, +5, +6] },
  { id: 'Am', name: 'أمريسيوم', symbol: 'Am', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 32, valency: '+3', oxidationStates: [+3, +4, +5, +6] },
  { id: 'Cm', name: 'كوريوم', symbol: 'Cm', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 31, valency: '+3', oxidationStates: [+3] },
  { id: 'Bk', name: 'بركليوم', symbol: 'Bk', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 30, valency: '+3', oxidationStates: [+3, +4] },
  { id: 'Cf', name: 'كاليفورنيوم', symbol: 'Cf', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 29, valency: '+3', oxidationStates: [+3] },
  { id: 'Es', name: 'أينشتاينيوم', symbol: 'Es', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 28, valency: '+3', oxidationStates: [+3] },
  { id: 'Fm', name: 'فرميوم', symbol: 'Fm', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 27, valency: '+3', oxidationStates: [+3] },
  { id: 'Md', name: 'مندليفيوم', symbol: 'Md', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 26, valency: '+3', oxidationStates: [+3] },
  { id: 'No', name: 'نوبليوم', symbol: 'No', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 25, valency: '+2', oxidationStates: [+2, +3] },
  { id: 'Lr', name: 'لورنسيوم', symbol: 'Lr', color: 'bg-rose-400', textColor: 'text-slate-800', radius: 24, valency: '+3', oxidationStates: [+3] },

  // Polyatomic Ions - bg-cyan-600
  { id: 'SO4', name: 'كبريتات', symbol: 'SO₄²⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 40, valency: '-2', oxidationStates: [-2] },
  { id: 'NO3', name: 'نترات', symbol: 'NO₃⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 38, valency: '-1', oxidationStates: [-1] },
  { id: 'OH', name: 'هيدروكسيد', symbol: 'OH⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 35, valency: '-1', oxidationStates: [-1] },
  { id: 'NH4', name: 'أمونيوم', symbol: 'NH₄⁺', color: 'bg-cyan-600', textColor: 'text-white', radius: 38, valency: '+1', oxidationStates: [+1] },
  { id: 'CO3', name: 'كربونات', symbol: 'CO₃²⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 40, valency: '-2', oxidationStates: [-2] },
  { id: 'PO4', name: 'فوسفات', symbol: 'PO₄³⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 42, valency: '-3', oxidationStates: [-3] },
  { id: 'C2H3O2', name: 'أسيتات', symbol: 'C₂H₃O₂⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 45, valency: '-1', oxidationStates: [-1] },
  { id: 'HCO3', name: 'بيكربونات', symbol: 'HCO₃⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 40, valency: '-1', oxidationStates: [-1] },
  { id: 'CrO4', name: 'كرومات', symbol: 'CrO₄²⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 42, valency: '-2', oxidationStates: [-2] },
  { id: 'MnO4', name: 'برمنجنات', symbol: 'MnO₄⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 41, valency: '-1', oxidationStates: [-1] },
  { id: 'CN', name: 'سيانيد', symbol: 'CN⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 35, valency: '-1', oxidationStates: [-1] },
];

export const COMMON_COMPOUNDS: { name: string; formula: string }[] = [
  { name: 'ماء', formula: 'H₂O' },
  { name: 'ملح الطعام', formula: 'NaCl' },
  { name: 'ثاني أكسيد الكربون', formula: 'CO₂' },
  { name: 'حمض الهيدروكلوريك', formula: 'HCl' },
  { name: 'حمض الكبريتيك', formula: 'H₂SO₄' },
  { name: 'هيدروكسيد الصوديوم', formula: 'NaOH' },
  { name: 'أمونيا', formula: 'NH₃' },
  { name: 'ميثان', formula: 'CH₄' },
  { name: 'بنزين', formula: 'C₆H₆' },
  { name: 'كربونات الكالسيوم', formula: 'CaCO₃' },
  { name: 'حمض الخليك', formula: 'CH₃COOH' },
  { name: 'جلوكوز', formula: 'C₆H₁₂O₆' },
  { name: 'نترات البوتاسيوم', formula: 'KNO₃' },
  { name: 'أكسيد الحديد (III)', formula: 'Fe₂O₃' },
  { name: 'بيكربونات الصوديوم', formula: 'NaHCO₃' },
];